"""add opening and closing time to space

Revision ID: 06116caca888
Revises: 6f69afaa3875
Create Date: 2026-09-14 11:19:08.891727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06116caca888'
down_revision: Union[str, Sequence[str], None] = '6f69afaa3875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('opening_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('space', sa.Column('closing_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'closing_time')
    op.drop_column('space', 'opening_time')
    # ### end Alembic commands ###
